# Generated by Django 2.1.15 on 2023-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=80)),
                ('Age', models.IntegerField()),
                ('Phone_No', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=300)),
                ('DOJ', models.DateField()),
            ],
        ),
    ]
