# Generated by Django 4.1.7 on 2023-04-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "permissions": [
                    ("bulk_download", "can do bulk download"),
                    ("bulk_upload", "can do bulk upload"),
                ]
            },
        ),
    ]
