# Generated by Django 4.1.7 on 2023-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=300)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
